apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" . }}
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: {{ include "nifi.fullname" . }}-transport@kubernetescrd
  labels:
    app.kubernetes.io/name: {{ include "nifi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "nifi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.nifi.web.httpsPort }}
